;; window-sysytemが有効の時のみ初期化
(when (window-system)
  ;; color-theme
  ;; (load-theme 'deeper-blue t)
  ;; (load-theme 'manoj-dark t)
  ;; (load-theme 'misterioso t)
  ;; (load-theme 'tango-dark t)
  ;; (load-theme 'wheatgrass t)
  ;; (load-theme 'wombat t)
  ;; (load-theme 'material t)
  ;; (load-theme 'ample t)
  ;; (load-theme 'ample-flat t)
  ;; (load-theme 'badwolf t)
  ;; (load-theme 'bliss t)
  ;; (load-theme 'bubbleberry t)
  ;; (load-theme 'clues t)
  ;; (load-theme 'cyberpunk t)
  ;; (load-theme 'gotham t)
  ;; (load-theme 'heroku t)
  ;; (load-theme 'kooten t)
  ;; (load-theme 'metalheart t)
  ;; (load-theme 'paganini t)
  (load-theme 'tronesque t)
  ;; (load-theme 'challenger-deep t)
  ;; (load-theme 'slime t)
  ;; (load-theme 'ubuntu t)
  )
;; (enable-theme 'ample)
